### Get Contacts

# Get all contacts
GET http://localhost:8080/contacts

# Get a specific contact by ID
GET http://localhost:8080/contacts/650f42d10e140e797b890f54

GET http://localhost:8080/contacts/650f42d10e140e797b890f55

GET http://localhost:8080/contacts/650f42d10e140e797b890f56
