### Get Contacts

# Get all contacts LOCALHOST
GET http://localhost:8080/contacts

# Get a specific contact by ID LOCALHOST
###
GET http://localhost:8080/contacts/650f42d10e140e797b890f54
###
GET http://localhost:8080/contacts/650f42d10e140e797b890f55
###
GET http://localhost:8080/contacts/650f42d10e140e797b890f56

#################################################

# Get all contacts RENDER
GET http://localhost:8080/contacts

# Get a specific contact by ID RENDER
###
GET http://localhost:8080/contacts/650f42d10e140e797b890f54
###
GET http://localhost:8080/contacts/650f42d10e140e797b890f55
###
GET http://localhost:8080/contacts/650f42d10e140e797b890f56
